name: Commitlint

on:
  push:
    branches:
      - main
      - workflow
  pull_request:
    branches:
      - main
      - workflow

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: wagoid/commitlint-github-action@v4
        with:
          configFile: 'commitlint.config.js'
          firstParent: false
          failOnWarnings: false
