name: Commitlint

on:
  push:
    branches:
      - main
      - workflow
  pull_request:
    branches:
      - main
      - workflow

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - uses: wagoid/commitlint-github-action@v5
        with:
          configFile: 'commitlint.config.cjs'
          failOnWarnings: false